;ADDITION AND SUBTRACTION OF TWO 8-BIT NUMBERS

ORG 0000H
MOV R1,#91H
MOV R2,#93H
MOV A,R1
ADDC A,R2
MOV R3,A  ;LOWER BYTE OF ADDITION RESULT
MOV A,#00H
ADDC A,#00H
MOV R4,A  ;HIGHER BYTE OF ADDITION RESULT
CLR C
MOV A,R2
SUBB A,R1
MOV R5,A  ;RESULT OF SUBTRACTION
S:SJMP S
END
