;READ 2 DATA BLOCKS OF 10 ELEMENTS EACH, STORE FROM 40H & 50H, EXCHANGE THEM

ORG 0000H
MOV R0,#40H ;ADDRESS  FOR STORING 1ST DATA BLOCK
MOV R1,#50H ;ADDRESS  FOR STORING 2ND DATA BLOCK
MOV R2,#0AH ;COUNT OF 10 NUMBERS

L:MOV A,P1 ;LOOP FOR ACCEPTNG ELEMENTS OF 1ST DATA BLOCK
MOV @R0,P1 ;STORING ELEMENTS FROM 40H ONWARDS
INC R0
DJNZ R2,L

MOV R2,#0AH

L1:MOV A,P2 ;LOOP FOR ACCEPTNG ELEMENTS OF 2ND DATA BLOCK
MOV @R1,A ;STORING ELEMENTS FROM 50H ONWARDS
INC R1
DJNZ R2,L1

MOV R0,#40H
MOV R1,#50H
MOV R2,#0AH

L2:MOV A,@R0 ;LOOP FOR EXCHANGING THE 2 BLOCKS
MOV B,@R1
MOV @R0,B
MOV @R1,A
INC R0
INC R1
DJNZ R2,L2

S:SJMP S
END