;SEQUENTIALLY GLOW ALL LEDS FROM 1ST TO LAST ONE AT A  TIME & TOGGLE EVERY 1 SECOND

ORG 0000H

L:MOV A,#01H
MOV R3,#08H
LA:MOV P1,A
RL A
LCALL DELAY
DJNZ R3,LA

SJMP L

DELAY:
MOV TMOD,#10H ;TIMER 1 MODE  1
MOV R2,#10H ;RUNS THE LOOP 16 TIMES i.e 1.04sec delay
LL:MOV TL1,#00H
MOV TH1,#00H
SETB TR1 ;STARTS TIMR 1
L1:JNB TF1,L1 ;POLLING;MONITORS OVERFLOW
CLR TR1
CLR TF1
DJNZ R2,LL
RET
END
