;ALTERNATELY TOGGLE 4 LEDS ON AND OFF EVERY 1.5 SECOND 

ORG 0000H

L:MOV A,#0FH ;1ST 4 LEDS OFF AND  NEXT 4 ON
MOV P1,A 
LCALL DELAY

MOV A,#0F0H ;1ST 4 LEDS ON AND NEXT 4 OFF
MOV P1,A
LCALL DELAY

SJMP L

DELAY:
MOV TMOD,#10H ;TIMER 1 MODE  1
MOV R2,#17H ;RUNS THE LOOP 23 TIMES i.e 1.5 sec delay
LL:MOV TL1,#00H
MOV TH1,#00H
SETB TR1 ;STARTS TIMER 1
L1:JNB TF1,L1 ;POLLING;MONITORS OVERFLOW
CLR TR1
CLR TF1
DJNZ R2,LL
RET
END
