;TOGGLE ALL LEDS ON AND OFF EVERY 1 SECOND

ORG 0000H

L:MOV A,#00H ;ALL 8 LEDS OFF
MOV P1,A
LCALL DELAY

MOV A,#0FFH ;ALL 8 LEDS ON
MOV P1,A
LCALL DELAY

SJMP L

DELAY:
MOV TMOD,#10H ;TIMER 1 MODE  1
MOV R2,#10H ;RUNS THE LOOP 16 TIMES i.e 1.04sec delay
LL:MOV TL1,#00H ;GIVES MAXIMUM delay i.e 65536 usec
MOV TH1,#00H ;GIVES MAXIMUM delay i.e 65536 usec
SETB TR1 ;STARTS TIMER 1
L1:JNB TF1,L1 ;POLLING;MONITORS OVERFLOW
CLR TR1
CLR TF1
DJNZ R2,LL
RET
END
