;FIND LARGEST AND SMALLEST NUMBER FROM THE DATA BLOCK

ORG 0000H
MOV R2,#0AH ;COUNT OF 10 NUMBERS
MOV R0,#40H ;START OF DATA BLOCK
L:MOV A,P1 ;LOOP FOR ACCEPTING 10 NUMBERS
MOV @R0,A ;STORES NUMBERS FROM 40H ONWARDS
INC R0
DJNZ R2,L

MOV R2,#0AH
MOV R0,#40H
MOV A,@R0 ;1ST VALUE OF DATA BLOCK IN A
INC R0 ;START ADDRESS OF DATA BLOCK INCREMENTED BY 1
L1:MOV B,@R0 ;2ND VALUE OF DATA BLOCK IN B
INC R0 ;START ADDRESS OF DATA BLOCK INCREMENTED BY 1
CJNE A,B,DN ;IF A AND B ARE NOT EQUAL
JMP NEXT
DN:JC L2 ;IF B IS GREATER
MOV 30H,A ;IF A IS GREATER
JMP NEXT
L2:MOV A,B 
MOV 30H,A ;MOVE ONLY GREATER NUMBER IN 30H
NEXT:DJNZ R2,L1 ;CONTINUE TILL ALL 10 NUMBERS ARE COMPARED

MOV R2,#0AH
MOV R0,#40H
MOV A,@R0
INC R0
L3:MOV B,@R0
INC R0
CJNE A,B,DN1 ;IF A AND B ARE NOT EQUAL
JMP NEXT1
DN1:JNC L4 ;IF A IS GREATER
MOV 31H,A ;IF B IS GREATER
JMP NEXT1
L4:MOV A,B
MOV 31H,A ;MOVE ONLY SMALLER NUMBER IN 31H
NEXT1:DJNZ R2,L3 ;CONTINUE TILL ALL 10 NUMBERS ARE COMPARED
S:SJMP S
END