;DISPLAY HELLO ON SEVEN SEGMENT DISPLAY WITH 2 SEC DELAY BETWEEN EACH CHARACTER

ORG 70H
DB 76H,79H,38H,38H,3FH ;LOOKUP TABLE VALUES

ORG 00H
MOV P1,#00H ; PORT1 OUTPUT
L4:MOV DPTR,#70H  ;STARTING ADDRESS OF LOOKUPTABLE
   MOV R2,#05 ;NUMBER OF CHARACTERS TO BE DISPLAYED
L: MOV A,#00H
   MOVC A,@A+DPTR
   INC DPTR
   MOV P1,A
   LCALL DELAY
DJNZ R2,L
SJMP L4

DELAY :
MOV TMOD,#10H ;TIMER 1 MODE 1
MOV R3,#20H ;GIVES DELAY OF 2 SEC; RUNS LOOP 32 TIMES
L3: MOV TL1,#00H ;lOWER BYTE OF COUNT
	MOV TH1,#00H ;HIGHER BYTE OF COUNT
	SETB TR1
	L2: JNB TF1,L2 ;CHECKING TIMER OVERFLOW; polling
		CLR TR1
		CLR TF1
DJNZ R3,L3
RET
END