;TO DISPLAY "MICROCONTROLLER ON LCD USING LOOK UP TABLE"

ORG 70H
DB 4DH, 49H,43H,52H,4FH,43H,4FH,4EH,54H,52H,4FH,4CH,4CH,45H,52H

ORG 0000H
MOV R2,0FH
MOV P1,#00H
MOV DPTR,#70H
MOV A,#38H  ;INITIALIZE 2 LINE DISPLAY
ACALL COMMAND
MOV A,#0EH  ;CURSOR ON,DISPLAY ON
ACALL COMMAND
MOV A,#01H  ;CLEAR LCD COMMAND
ACALL COMMAND
MOV A,#06H  ;SHIFT CURSOR RIGHT
ACALL COMMAND
;MOV A,#86H  ;CURSOR LINE 1
;ACALL COMMAND

L:  MOV A,#00H
	MOVC A,@A+DPTR
	MOV P1,A
	SETB P2.0 ;RS=1-->REGISTER SELECT-->DATA REGISTER
	CLR P2.1   ;RW=0-->WRITE OPERATION
	CLR P2.2  ;E=0-->ENABLE SIGNAL IS LOW
	LCALL DELAY1
	SETB P2.2 ;E=1-->ENABLE SIGNAL IS HIGH
	MOV A,#06H 
	ACALL COMMAND
	INC DPTR
	DJNZ R2,L

DELAY1:
	MOV TMOD,#10H
	MOV TH1,#00H
	MOV TL1,#00H
	SETB TR1
	L1: JNB TF1,L1
		CLR TR1
		CLR TF1
	RET

COMMAND:
	MOV P1,A
	CLR P2.0 ;RS=0-->REGISTER SELECT-->COMMAND REGISTER
	CLR P2.1 ;RW=0-->WRITE OPERATION
	CLR P2.2 ;E=0-->ENABLE SIGNAL IS LOW
	LCALL DELAY1
	SETB P2.2 ;E=1-->ENABLE SIGNAL IS HIGH
	RET
END 