;DISPLAY MESSAGE "WELCOME" AND CONTINOUSLY SCROLL FROM LEFT TO RIGHT

ORG 70H
DB 57H,45H,4CH,43H,4FH,4DH,45H

ORG 00H
MAIN:
MOV A,#38H  ;2 LINE 
ACALL COMMAND
MOV A,#0EH  ;CURSOR ON
ACALL COMMAND
MOV A,#86H  ;CURSOR LINE 1
ACALL COMMAND
MOV A,#01H  ;CLEAR LCD COMMAND
ACALL COMMAND
MOV A,#06H  ;SHIFT CURSOR RIGHT
ACALL COMMAND

MOV P1,#00H
MOV DPTR,#70H ;START OF DATA BLOCK
MOV R2,#07H ;NO OF CHARACTERS TO BE DISPLAYED

L:  MOV A,#00H
	MOVC A,@A+DPTR
	MOV P1,A
	SETB P2.0 ;RS=1-->REGISTER SELECT-->DATA REGISTER
	CLR P2.1   ;RW=0-->WRITE OPERATION
	CLR P2.2  ;E=0-->ENABLE SIGNAL IS LOW
	LCALL DELAY1
	SETB P2.2 ;E=1-->ENABLE SIGNAL IS HIGH
	MOV A,#06H ;SHIFT CURSOR RIGHT
	ACALL COMMAND
	INC DPTR
	DJNZ R2,L

MOV R2,#07H
K: MOV A,#1CH ;SHIFTS THE ENTIRE DISPLAY TO RIGHT(SCROLL)
LCALL COMMAND
DJNZ R2,K
SJMP MAIN

COMMAND: ;FOR DISPLAYING
	MOV P1,A
	CLR P2.0  ;RS=0-->REGISTER SELECT-->COMMAND REGISTER
	CLR P2.1  ;RW=0-->WRITE OPERATION
	CLR P2.2  ;E=0-->ENABLE SIGNAL IS LOW
	LCALL DELAY1
	SETB P2.2 ;E=1-->ENABLE SIGNAL IS HIGH
RET

DELAY1: ;DELAY BETWEEN 2 CHARACTERS
	MOV TMOD,#10H ;TIMER 1 MODE 1
	MOV TH1,#00H
	MOV TL1,#00H
	SETB TR1
	L1: JNB TF1,L1
		CLR TR1
		CLR TF1
RET
END 